# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_tag',
            field=models.CharField(choices=[('i', 'iOS'), ('p', 'Python'), ('g', 'git/svn'), ('j', 'javascript'), ('e', 'essay')], max_length=10),
        ),
    ]
