# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161217_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tag',
            field=models.CharField(choices=[('iOS', 'i'), ('python', 'p'), ('git/svn', 'g'), ('javascript', 'j'), ('essay', 'e')], max_length=10),
        ),
    ]
